### ISSUE TITLE
Problems installing on Webos 3 LG OLED A1

### ISSUE THREAD

**Issue by EnriqueWood** [WillinuX-Code/webos-tvheadend#19]
![20230310_175926.jpg](https://user-images.githubusercontent.com/22996504/224427546-d4f64fd6-4ed9-4cda-8222-79808e17783b.jpg)

It's showing the error described in the image.

TV Software version is 03.34.70

**Comment by WillinuX-Code** [comment]
It looks more like a general hombrew issue. Are you able to install any of the ther apps in the hombrew channel?

**Comment by EnriqueWood** [comment]
Yes, I have some others apps installed without problems

**Comment by WillinuX-Code** [comment]
Hi Enrique, 
you said "you have installed". My question is are you currently able to install another new app from the homebrew browser?

The installation process is part of the homebrew browser app. Therefore I would recommend to report this issue there.
Brgds

**Comment by krix** [comment]
I just stumbled upon this:

![4365B0F5-61C3-4044-842A-13A5BFBB7D7E](https://user-images.githubusercontent.com/169311/224441040-85d89b8e-d41a-4366-8b95-37c98c033584.jpeg)

Can you check that you have enabled „dev mode“?

I hope you find a solution, soon!

Best regards

**Comment by Informatic** [comment]
Hey, that definitely sounds like a Homebrew Channel issue. This should probably be [filed there](https://github.com/webosbrew/webos-homebrew-channel/issues).
