### ISSUE TITLE
Release manifest invalid source URL

### ISSUE THREAD

**Issue by Informatic** [WillinuX-Code/webos-tvheadend#20]
Hey!

Latest application release manifest contains the following invalid URL in `sourceUrl` field: `https://raw.githubusercontent.com/willinuX-code/webos-tvheadend`

Not a big deal, but we do render it in a couple of places like Homebrew Channel app info view and https://repo.webosbrew.org/apps/com.willinux.tvh.app - you should be able to just reupload fixed manifest file and webosbrew apps-repo automation will refetch it automatically after a while.

It would also be really nice if some specific license you're releasing this under was mentioned anywhere in the repo, like a README or relevant `package.json` field.

**Comment by WillinuX-Code** [comment]
Hey,
thanks for the information.
I updated the manifest and added a licence file.
Brgds
Jens
