### ISSUE TITLE
Socket hang up for Stream on Connection Test

### ISSUE THREAD

**Issue by britgomi** [WillinuX-Code/webos-tvheadend#24]
Hello,

Thanks for nurturing this awesome project.

I have been trying the app on my LG OLED GX with my Tvheadend server, but it seems to run into "socket hang up" issue during the connection test.

I have my streaming profile set as "Pass" on Tvheadend, tried different profiles, mkv and transcoding to no avail.

Attaching a screen of the issue, my details as well.

TV: LG OLED65WXPCA
WebOS Version: 04.40.16
Tvheadend Build: 4.3-2027~ge3f4f222e (2022-07-12T14:51:28+0000)

![Screenshot 2023-03-28 1047571](https://user-images.githubusercontent.com/129167793/228200427-02472915-1ba4-48dd-967d-46856eddc132.png)

**Comment by WillinuX-Code** [comment]
Streaming Profile "pass" should be fine.

- Do you have "simple" and "advanced" checked in the "streaming" section of the user settings in tvheadend?
- Do you have the "persistent authentication" activated for your user? You can find this in the passwords section.

**Comment by britgomi** [comment]
Thanks for your quick reply.

• During the stream test the first channel in the list is used. You can check if this channel is actually working. Not sure if this is just caused by a failing channel?

This made it for me, it was indeed the first channel not able to stream.
