### ISSUE TITLE
Volume very low for ARTE channel

### ISSUE THREAD

**Issue by jclsn** [WillinuX-Code/webos-tvheadend#31]
The volume for ARTE is very low. I have no problem with other TVHeadend clients, so the issue must be here. I have not found any other channel that has this problem.

The channel can be found [here](https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/iptv/pipe/pipe_tv_main.m3u) 

Any ideas how to fix this?

**Comment by WillinuX-Code** [comment]
The app itself has no volume handling/control or anything like it. This is handled on a higher level by the TV OS

**Comment by jclsn** [comment]
All other channels have normal volume. This is really mysterious.

**Comment by jclsn** [comment]
Works now for whateever reason
